version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: app_tjjud
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app_tjjud

  nginx:
    image: nginx:latest
    container_name: tjjud_nginx
    ports:
      - "8074:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_tjjud

  db:
    image: mysql:8
    container_name: tjjud_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tjjud_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
    ports:
      - "33067:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app_tjjud

networks:
  app_tjjud:
    driver: bridge

volumes:
  dbdata: